version: '2'
services:

 proxy:
  image: vimagick/dante
  restart: always
  ports:
   - "1080:1080"

 nodepki:
  image: adito/nodepki-docker
  depends_on:
   - proxy
  volumes:
   - certs:/certs
   - data:/root/nodepki/data
   - data:/root/nodepki-client/data
   - data:/root/nodepki-webclient/data
   - ./applications/nodepki/data/config:/root/nodepki/data/config
   - ./applications/nodepki-client/data/config:/root/nodepki-client/data/config
   - ./applications/nodepki-webclient/data/config:/root/nodepki-webclient/data/config
   - ./applications/nodepki-webclient/api/webclient/controllers/request.js:/root/nodepki-webclient/controllers/request.js
  environment:
   - API_USERNAME=${API_USERNAME}
   - API_PASSWORD=${API_PASSWORD}

 rabbitmq:
  image: marcelmaatkamp/rabbitmq-mqtt-ldap
  restart: always
  hostname: rabbitmq
  environment:
   - RABBITMQ_NODENAME=rabbitmq@rabbitmq
  ports:
   - 5671:5671
  volumes:
   - certs:/certs
   - rabbitmq:/var/lib/rabbitmq/mnesia
   - ./applications/rabbitmq/etc/rabbitmq.config:/etc/rabbitmq/rabbitmq.config

 server1:
  image: node
  command: node /application/server.js
  environment:
   - SERVERNAME=server1
  volumes:
   - ./applications/server:/application
   - certs:/certs

 server2:
  image: node
  command: node /application/server.js
  environment:
   - SERVERNAME=server2
  volumes:
   - ./applications/server:/application
   - certs:/certs

volumes:
 data:
 certs:
 rabbitmq:
